/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');

module.exports = {
  // TypeScript generation
  typescript: true,

  // Adds viewBox and optimizes for icons
  icon: true,

  // Export without "Svg" prefix
  exportType: 'named',

  // Filenames in kebab-case (modern style)
  filenameCase: 'kebab',

  // Use custom template
  template: require('./svgr-template.cjs'),

  // Don't format with prettier (using our own formatter)
  prettier: false,

  // SVGO optimization
  svgoConfig: {
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            // Keep viewBox for proper scaling
            removeViewBox: false,
            // Remove unnecessary attributes
            cleanupIds: true,
          },
        },
      },
      // Custom plugin: replace ALL colors (fill/stroke) with currentColor
      // This allows controlling color via className="text-color-500"
      {
        name: 'convertColorsToCurrentColor',
        fn: () => {
          return {
            element: {
              enter: (node) => {
                // Replace fill with currentColor (except 'none')
                if (node.attributes.fill && node.attributes.fill !== 'none') {
                  node.attributes.fill = 'currentColor';
                }
                // Replace stroke with currentColor (except 'none')
                if (node.attributes.stroke && node.attributes.stroke !== 'none') {
                  node.attributes.stroke = 'currentColor';
                }
              },
            },
          };
        },
      },
    ],
  },

  // Add props to SVG element
  svgProps: {
    className: '{cn(className)}',
  },

  // Index file for auto-export (preserves manually added exports)
  indexTemplate: (filePaths) => {
    // Build set of generated filenames (without extension)
    const generatedFiles = new Set(
      filePaths.map((filePath) =>
        filePath.path.split(/[\\/]/).pop().replace('.tsx', '')
      )
    );

    // Generate export lines for SVGR-generated files
    const generatedExports = filePaths.map((filePath) => {
      const filename = filePath.path.split(/[\\/]/).pop().replace('.tsx', '');
      const componentName = filename
        .split('-')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');
      return `export { ${componentName} } from './${filename}';`;
    });

    // Read existing index.ts and preserve exports that weren't generated by SVGR
    const indexPath = path.resolve(__dirname, 'src/components/icons/index.ts');
    let manualExports = [];

    try {
      const existing = fs.readFileSync(indexPath, 'utf-8');
      const lines = existing.split('\n').filter((line) => line.trim());

      for (const line of lines) {
        // Extract the module path from: export { Foo } from './bar';
        const match = line.match(/from\s+['"]\.\/([^'"]+)['"]/);
        if (match && !generatedFiles.has(match[1])) {
          manualExports.push(line);
        }
      }
    } catch {
      // index.ts doesn't exist yet — nothing to preserve
    }

    return [...generatedExports, ...manualExports].join('\n') + '\n';
  },
};
